# Why Use PyTorch?

PyTorch is an open-source machine learning library for Python, developed primarily by Facebook's artificial intelligence research group. The main reason why PyTorch has gained popularity is its complete ease of use and flexibility.

![PyTorch Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png)



## Dynamic Computation Graphs

A key feature that differentiates PyTorch from other deep learning libraries is its dynamic computation graph.

- A computation graph is an abstract way to represent your mathematical computations which are happening in the code.
- The graph is essential as it allows you to not only visualize the computation but also compute the gradients automatically.
- [Computation Graph Blog](https://towardsdatascience.com/getting-started-with-pytorch-part-1-understanding-how-automatic-differentiation-works-5008282073ec)

In static computation graph (used in libraries like TensorFlow), the graph is defined in advance and then executed. However, in Pytorch:
- Operations can be executed immediately, making debugging easier.
- The overall experience is closer to the usual Python programming.



## Role of Differentiation and Chain Rule

Differentiation is a crucial part of any deep learning library.

- PyTorch uses a technique called automatic differentiation, which numerically evaluates the derivative of a function.
- It is beneficial when dealing with complex equations, such as the ones we encounter in deep learning models.

The Chain Rule:
- It is used for differentiating compositions of functions.
- This rule is central to backpropagation which is used for training neural networks.
- The ability to compute gradients or derivatives of our error or loss with respect to our model's parameters, using the chain rule, allows us to optimize our model.

# A Beginner's Guide to Tensors

## What is a Tensor?

Just as kids can arrange their toys in many ways, data in computing can also be arranged in various forms. Imagine you're in a toy store.

- An action figure sitting alone represents a single number, also known as a **scalar** in mathematics. A scalar only has a magnitude (its price in our case).
- Action figures arranged in a row represent a one-dimensional array, popularly known as a **vector** in computing and mathematics.
- Multiple rows and columns of action figures showcased in a glass box constitute a two-dimensional array or a **matrix**.
- And lastly, a pile of such glass boxes stacked over each other forms a three-dimensional array, known as a **tensor**.

A tensor, in essence, can house data in N dimensions but visualizing dimensions beyond the third one can be quite challenging.


## Tensors in PyTorch

In the context of PyTorch (a popular library for deep learning), a tensor is pretty similar to NumPy's ndarray, and serves as the core data structure of the library.

The three main components associated with tensors in PyTorch are:

- **Grad**: It holds the value of gradient. PyTorch provides automatic differentiation and gradient computation which is executed when `.backward()` function is called.

- **Grad_fn**: It is the backward function through which the gradient has been computed.

- **Data**: This gives access to the raw data of the tensor.


#pyTorch hands on


In [40]:
import torch

In [44]:
t1 = torch.tensor([123]) # list
print(t1)

tensor([123])


In [45]:
t2 = torch.tensor([1, 3, 56]) # list
t2

tensor([ 1,  3, 56])

In [47]:
t3 = torch.tensor([[71, 63, 56], [41, 33, 36], [12, 13, 56]]) #matrix or 2d array
t3

tensor([[71, 63, 56],
        [41, 33, 36],
        [12, 13, 56]])

In [53]:
t4 = torch.rand((2, 2, 3,  4)) # 4d tensor
t4

tensor([[[[0.0489, 0.9811, 0.4841, 0.4563],
          [0.3645, 0.2804, 0.5648, 0.4291],
          [0.9350, 0.4427, 0.5392, 0.8962]],

         [[0.7038, 0.4302, 0.4793, 0.7330],
          [0.0926, 0.9524, 0.0857, 0.2026],
          [0.9109, 0.0585, 0.2108, 0.7303]]],


        [[[0.1812, 0.4382, 0.7901, 0.5384],
          [0.5782, 0.1085, 0.7891, 0.9329],
          [0.6105, 0.7977, 0.8257, 0.6815]],

         [[0.6770, 0.2644, 0.1489, 0.8949],
          [0.0603, 0.9511, 0.7097, 0.5604],
          [0.4057, 0.6561, 0.9403, 0.4030]]]])

In [55]:
t5 = torch.rand((2, 2, 2, 3,  4)) # 5d tensor
t5

tensor([[[[[0.0195, 0.0718, 0.0408, 0.4122],
           [0.1932, 0.3714, 0.1908, 0.5408],
           [0.9145, 0.2711, 0.3356, 0.0522]],

          [[0.7831, 0.5051, 0.2124, 0.3839],
           [0.6802, 0.2406, 0.5145, 0.6626],
           [0.7313, 0.0279, 0.7054, 0.2339]]],


         [[[0.7337, 0.8441, 0.1138, 0.5090],
           [0.9958, 0.7904, 0.9044, 0.6528],
           [0.3413, 0.8062, 0.3226, 0.4173]],

          [[0.4480, 0.7880, 0.5059, 0.5101],
           [0.0024, 0.8525, 0.8226, 0.5282],
           [0.6375, 0.6496, 0.0796, 0.2182]]]],



        [[[[0.9428, 0.4299, 0.9727, 0.4544],
           [0.6792, 0.5054, 0.8887, 0.5914],
           [0.1302, 0.2394, 0.2619, 0.3313]],

          [[0.2020, 0.5461, 0.6350, 0.9905],
           [0.3647, 0.2360, 0.1910, 0.7543],
           [0.9175, 0.7514, 0.7033, 0.2516]]],


         [[[0.8499, 0.9880, 0.8369, 0.2252],
           [0.8480, 0.8535, 0.5727, 0.2377],
           [0.3985, 0.7663, 0.0709, 0.4141]],

          [[0.3798, 0.0128, 0.238

In [56]:
t1.shape, t2.shape, t3.shape, t4.shape, t5.shape,

(torch.Size([1]),
 torch.Size([3]),
 torch.Size([3, 3]),
 torch.Size([2, 2, 3, 4]),
 torch.Size([2, 2, 2, 3, 4]))

## Data types in Tensor

[All datatypes of Tensor in pyTorch](https://pytorch.org/docs/stable/tensors.html)

In [59]:
t_float = torch.tensor([1, 3, 56], dtype=torch.float64) # list
t_float

tensor([ 1.,  3., 56.], dtype=torch.float64)

##Math Operations on Tensors


In [61]:

# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print("Absolute", torch.abs(a))
print("Ceiling", torch.ceil(a))
print("Floor", torch.floor(a))
print("Clamp", torch.clamp(a, -0.5, 0.5))

Common functions:
Absolute tensor([[0.6566, 0.5836, 0.3394, 0.7274],
        [0.6814, 0.4508, 0.8396, 0.6929]])
Ceiling tensor([[1., 1., 1., -0.],
        [-0., 1., 1., 1.]])
Floor tensor([[ 0.,  0.,  0., -1.],
        [-1.,  0.,  0.,  0.]])
Clamp tensor([[ 0.5000,  0.5000,  0.3394, -0.5000],
        [-0.5000,  0.4508,  0.5000,  0.5000]])


In [63]:
import math
# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)



Sine and arcsine:
tensor([0.0000, 3.1416, 0.7854, 1.5708, 2.3562])
tensor([ 0.0000e+00, -8.7423e-08,  7.0711e-01,  1.0000e+00,  7.0711e-01])
tensor([ 0.0000e+00, -8.7423e-08,  7.8540e-01,  1.5708e+00,  7.8540e-01])


In [65]:
# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool


Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])


##Tensor Reduction/Aggregation




In [71]:
# reductions:
d = torch.tensor([[1., 2.], [3., 4.]])
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


##Tensor Reduction/Aggregation along rows and columns



In [70]:
# reductions:
d = torch.tensor([[1., 2.], [3., 4.]])
print('\nReduction ops:')
print(torch.mean(d))       # average
print(torch.mean(d, dim=1))       # average each row
print(torch.mean(d, dim=0))       # average each col


Reduction ops:
tensor(2.5000)
tensor([1.5000, 3.5000])
tensor([2., 3.])


#Manipulating Tensor Shapes
- This is the one of the most important if not the most important topic.

In [78]:
a = torch.rand(2, 3, 4)
a.shape


torch.Size([2, 3, 4])

In [80]:
a

tensor([[[0.7132, 0.4561, 0.4247, 0.8297],
         [0.8061, 0.6957, 0.3318, 0.5511],
         [0.1921, 0.1468, 0.1033, 0.5926]],

        [[0.2604, 0.6975, 0.6360, 0.4886],
         [0.5887, 0.4280, 0.0127, 0.4609],
         [0.2093, 0.2102, 0.1929, 0.3554]]])

In [83]:
a.view(-1, 1).shape, a.view(-1, 2).shape

(torch.Size([24, 1]), torch.Size([12, 2]))

In [87]:
# you dont need -1 all the time, if you know the exact dim, then you can use that
# 2x3x4 = total 24

a.view(4, 6), a.view(4, 6).shape

(tensor([[0.7132, 0.4561, 0.4247, 0.8297, 0.8061, 0.6957],
         [0.3318, 0.5511, 0.1921, 0.1468, 0.1033, 0.5926],
         [0.2604, 0.6975, 0.6360, 0.4886, 0.5887, 0.4280],
         [0.0127, 0.4609, 0.2093, 0.2102, 0.1929, 0.3554]]),
 torch.Size([4, 6]))

In [88]:
# you dont need -1 all the time, if you know the exact dim, then you can use that
# 2x3x4 = total 24

a.view(4, 10)

RuntimeError: shape '[4, 10]' is invalid for input of size 24

# Rand vs Randn
- Rand gives random number from 0 to 1
- Randn also gives random number from a normal distribution where mean is 0 and variance of 1

In [92]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [97]:
torch.randn(2, 3)

tensor([[0.4528, 0.6410, 0.5200],
        [0.5567, 0.0744, 0.7113]])

In [99]:
# random integers between 3 and 10, 10 excluded of the provided shape
x = torch.randint(3, 10, (3, 4))
x

tensor([[9, 6, 3, 4],
        [9, 6, 7, 5],
        [9, 8, 7, 8]])

In [100]:
torch.numel(x) # number of elements in the tensor, in this case, 3x4 = 12

12

#Zeros, Ones, and Likes

# Practical UseCases for PyTorch's `torch.ones`, `zeros`, `like`

PyTorch provides several functions to create tensors. Three of them are `torch.ones`, `torch.zeros`, and `torch.ones_like`, `torch.zeros_like`. Let's take a look at practical scenarios where these can be used.

## torch.ones

`torch.ones` is used to create a tensor filled with the scalar value 1, with the shape defined by the variable argument size.

### Use case:
- Initialization of bias or weights in a neural network: `torch.ones` can be used fill the weights or bias tensor with initial value of 1.

    ```python
    bias = torch.ones((10,))
    weights = torch.ones((5, 10))
    ```

- Generation of a mask tensor: For certain operations where we needs apply a mask to all elements.

    ```python
    mask = torch.ones_like(weights)
    ```

## torch.zeros

`torch.zero` creates a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

### Use case:
- Creation of a black image or background in computer vision tasks.
    ```python
    black_img = torch.zeros([256, 256, 3])
    ```
- Padding values in data analytics.
    ```python
    padded_sequence = torch.zeros(max_sequence_length, dtype=int)
    padded_sequence[:len(sequence)] = torch.tensor(sequence)
    ```
- In deep learning, to initialize the weights or bias tensor with zeros before training.
    ```python
    weights = torch.zeros((5, 10))
    ```
- Generation of a masking tensor.

## torch.ones_like and torch.zeros_like

These functions come handy when ones need to create a new tensor that has the same size as a given tensor. The new tensor is then filled with ones or zeros respectively.

### Use case:

```python
x = torch.randn((5, 5))

# creating tensor with same size as x
ones = torch.ones_like(x)
zeros = torch.zeros_like(x)
```

Operations like initializing tensors, creating masks, generating images, and padding sequences are just some of the areas where these functions are vital. Their application is versatile and extend to many other fields of machine learning, deep learning and data analytics.

In [101]:
ones = torch.ones((2, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
ones = torch.ones((2, 4), dtype=torch.float64)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [104]:
zeros = torch.zeros((2, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [105]:
new_tensor = torch.rand_like(zeros, dtype=torch.float64)
new_tensor

tensor([[0.8456, 0.3843, 0.0993, 0.6626],
        [0.5819, 0.7093, 0.4720, 0.0938]], dtype=torch.float64)

In [106]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1, 2, 3])

t3 = t1.add(t2)
t3

tensor([2, 4, 6])

In [107]:
t1, t2

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [108]:
# inplace addition. Similarly you can do any operation inplace
t1.add_(t2)
t1

tensor([2, 4, 6])

# Understanding AutoGrad

PyTorch's `autograd` package provides classes and functions implementing automatic differentiation of arbitrary scalar-valued functions. It allows for on-the-fly operation tracking on tensors, where every operation is recorded on a graph. The graph is then used in the backward pass to compute gradients.

## Definition of Autograd

`autograd` is PyTorch’s automatic differentiation library. It keeps a record of all operations performed on a tensor and creates an acyclic computation graph. This allows the use of back-propagation to calculate the gradients of the weights with respect to the loss function, which is essential when training neural networks.

## Importance of Autograd

In machine learning, especially in neural networks, optimization of weights is done using gradient information. Gradients point the optimizer in the direction towards which the parameters should be altered for minimizing the loss function. Autograd automates the computation of the backward pass in a computational graph (which are the gradients). Hence, calculation of gradients is performed automatically and accurately.

## How Autograd works

- When a tensor's `.requires_grad` property is set as `True`, PyTorch starts to track all operations on it.
- After the computation is finished, `.backward()` is called and all gradients are computed automatically.
- The gradient for a tensor will be accumulated into `.grad` attribute.
- To prevent tracking history and the use of memory, `.detach()` is called to stop tracking computations.
- Tracking can also be stopped by wrapping the code block inside `with torch.no_grad():`

Here is an example demonstrating autograd:

```python
x = torch.randn(3, 3, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out.backward()  # computes gradients
print(x.grad)  # the gradient of 'out' with respect to 'x'
```

## Conclusion

The usage of `autograd` simplifies the computation of gradients in neural networks. By automatically calculating gradients, it reduces the likelihood of making errors in complex neural networks, and hence improves efficiency of the model training phase.

In [133]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out

tensor(50., grad_fn=<MeanBackward0>)

In [134]:
# this wont work because backword is not yet called
print(x.grad)  # the gradient of 'out' with respect to 'x'

None


In [135]:
# before calling the backward, lets have a look at the grad functions of each

y.grad_fn, z.grad_fn, out.grad_fn

(<AddBackward0 at 0x7ff63979f220>,
 <MeanBackward0 at 0x7ff63979ec20>)

##The Backward Function

The `backward()` function in PyTorch is a critical part of the Autograd system, which is responsible for automatic computation of gradients for various operations on Tensors.




### Functionality of the `backward()` Function

The `backward()` function is primarily used for computing the gradients of the loss with respect to some set of variables (usually the model parameters). It performs backpropagation starting from a variable.

Here's how it works:

- The `backward()` function computes the gradient/differentiation of the current tensor w.r.t. graph leaves.
- The graph is defined by following all the operations from the leaf/leaves to the current tensor.
- If the current tensor (`y`) is a scalar (i.e., it holds a one-element data), then you don’t need to specify any arguments to `backward()`. However, if it has more elements, you need to specify a gradient argument that is a tensor of matching shape (to `y`).



### Example of how `backward()` works:

Here is a simple example:

```python
import torch

# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2, 2, requires_grad=True)

# Perform a tensor operation
y = x + 2

# Perform more operations on y
z = y * y * 3
out = z.mean()

# Trigger the backpropagation with backward()
out.backward()

# Print gradients d(out)/dx
print(x.grad)
```

In the above code:
- We first define a tensor `x` with `requires_grad=True` to ensure that the operation should be recorded for gradient computation.
- We then perform several operations on `x` to get the output tensor `out`.
- Calling the `backward` function triggers backpropagation, computation of the gradient.
- Finally, the gradients are available in `x.grad`.

### Conclusion

The `backward()` function is essential for neural network training. With this function, PyTorch allows automatic and efficient gradient computations. This simplifies the implementation of many machine learning algorithms, making development faster and less error-prone.

In [136]:
out.backward( )  # computes gradients
print(x.grad)  # the gradient of 'out' with respect to 'x'

tensor([ 6.,  8., 10.])


#Loss function in pyTorch
- [Every loss available in pyTorch](https://pytorch.org/docs/stable/nn.html#loss-functions)

In [137]:
import torch.nn as nn

In [143]:
#without any reduction
loss_mse = nn.MSELoss(reduction="none")
input = torch.randn(3, 4, requires_grad=True)
target = torch.randn(3, 4)
loss = loss_mse(input, target)
loss

tensor([[0.0107, 2.1891, 0.2098, 2.1428],
        [0.2858, 1.6717, 0.1127, 2.5816],
        [1.3416, 0.1585, 0.8656, 0.3567]], grad_fn=<MseLossBackward0>)

In [145]:
# in general we want to have one single value of the loss
loss_mse = nn.MSELoss(reduction="sum")
loss = loss_mse(input, target)
loss

tensor(11.9265, grad_fn=<MseLossBackward0>)

In [146]:
# in general we want to have one single value of the loss
loss_mse = nn.MSELoss(reduction="mean")
loss = loss_mse(input, target)
loss

tensor(0.9939, grad_fn=<MseLossBackward0>)